//! Serde mirror of the `claude -p --output-format stream-json
//! --include-partial-messages --verbose` wire shapes.
//!
//! Source of truth (live probe against `~/.claude` v2.1.121, see plan
//! `~/.claude/plans/review-this-project-and-polymorphic-rabbit.md`):
//!
//! ```text
//! echo '{"type":"user",...}' | claude -p \
//!   --input-format stream-json \
//!   --output-format stream-json \
//!   --include-partial-messages \
//!   --verbose \
//!   --dangerously-skip-permissions \
//!   --max-turns 1 --model haiku
//! ```
//!
//! Every line claude writes to stdout is one of `system | stream_event |
//! assistant | user | result | rate_limit_event`, tagged on the `type`
//! discriminator. We deserialize the envelope into [`ClaudeOutbound`] and
//! pass the parsed payload up to the bridge translator. Fields the bridge
//! does not introspect today are kept as `serde_json::Value` so additive
//! claude releases don't require a schema change.
//!
//! Translator-facing event broadcasted by the pool is [`ClaudeEvent`], which
//! wraps `ClaudeOutbound` verbatim — this crate is responsible only for
//! parsing and routing; codex-shaped translation happens in
//! `claude_translate` (owned by the `claude-translate` teammate).

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use serde_json::Value;

// ============================================================================
// Inbound: bridge → claude on stdin
// ============================================================================
//
// `claude -p --input-format stream-json` accepts one JSON object per stdin
// line. The wire shape is the Anthropic SDK `MessageParam` family wrapped in
// `{ "type": "user", "message": { ... } }`. Claude only consumes user-role
// messages on stdin (assistant/tool messages happen out-of-band via tool
// results inside its own loop), so we model just that one inbound variant.

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClaudeInbound {
    User(ClaudeUserMessageEnvelope),
    /// Out-of-band control message that drives a sidecar protocol on stdin
    /// (interrupt, set_model, rewind_files, ...). claude replies with a
    /// matching `control_response{request_id}` envelope; the bridge correlates
    /// via `pool::process`'s pending-control-response table.
    ControlRequest(ControlRequestEnvelope),
    /// Cancel a previously-sent control_request. Useful when the bridge
    /// changes its mind mid-flight (e.g. user closes the dialog while a
    /// pending `can_use_tool` response is still being composed). v2 wiring
    /// only — none of the handler paths originate cancellations today.
    ControlCancelRequest(ControlCancelEnvelope),
    /// Bridge replying to claude's inbound `control_request{can_use_tool|...}`
    /// when the bridge is acting as the tool-permission server (i.e. spawned
    /// with `--permission-prompt-tool stdio`). Wire shape mirrors the inbound
    /// `control_response` envelope — `request_id` lives nested inside the
    /// outer `response` object, NOT at top level.
    ControlResponse(OutboundControlResponseEnvelope),
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OutboundControlResponseEnvelope {
    pub response: OutboundControlResponseInner,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "subtype", rename_all = "snake_case")]
pub enum OutboundControlResponseInner {
    Success {
        request_id: String,
        /// Subtype-specific reply payload claude is waiting for. For
        /// `can_use_tool` this is `{behavior:"allow", updatedInput?, ...} |
        /// {behavior:"deny", message?, interrupt?, ...}`.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        response: Option<Value>,
    },
    Error {
        request_id: String,
        error: String,
    },
}

/// Wire shape: `{"type":"control_request","request_id":"<uuid>","request":{...subtype...}}`.
/// `request_id` is generated by [`crate::pool::process::ClaudeProcessHandle::request_control`]
/// so callers don't need to manage correlation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ControlRequestEnvelope {
    pub request_id: String,
    pub request: ControlRequestBody,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ControlCancelEnvelope {
    pub request_id: String,
}

/// Typed mirror of the SDK's outbound control_request `request` payloads (see
/// `~/dev/cc/node_modules/@anthropic-ai/claude-agent-sdk/sdk.mjs`, search for
/// `subtype:"`). Variants the bridge actually originates today are spelled
/// out for type safety; everything else degrades to [`ControlRequestBody::Other`]
/// so future SDK features remain forwardable without a schema bump.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "subtype", rename_all = "snake_case")]
pub enum ControlRequestBody {
    /// Aborts the in-flight turn. Claude replies with `subtype:"success"` or
    /// `subtype:"error"`. No request fields.
    Interrupt,
    /// Hot-swap the model for subsequent turns on the same process.
    SetModel { model: String },
    /// Toggle permission mode mid-thread (e.g. `default → bypassPermissions`).
    SetPermissionMode { mode: String },
    /// Cap the thinking budget in tokens.
    SetMaxThinkingTokens { tokens: u32 },
    /// Cancel a single subagent task by its task id.
    StopTask { task_id: String },
    /// Roll the on-disk transcript back to the supplied user message id.
    /// `dry_run:true` returns the would-be result without committing.
    RewindFiles {
        user_message_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        dry_run: Option<bool>,
    },
    /// SDK's first-frame initializer that registers hooks/MCP/etc. The bridge
    /// does not send this in v1 (we rely on the user-message-triggers-init
    /// quirk), but the variant is provided so a v2 cleaner-init-path
    /// experiment can flip to it without touching this enum.
    Initialize {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        hooks: Option<Value>,
        #[serde(
            default,
            rename = "sdkMcpServers",
            skip_serializing_if = "Option::is_none"
        )]
        sdk_mcp_servers: Option<Vec<String>>,
        #[serde(
            default,
            skip_serializing_if = "Option::is_none",
            rename = "jsonSchema"
        )]
        json_schema: Option<Value>,
        #[serde(
            default,
            skip_serializing_if = "Option::is_none",
            rename = "systemPrompt"
        )]
        system_prompt: Option<String>,
        #[serde(
            default,
            skip_serializing_if = "Option::is_none",
            rename = "appendSystemPrompt"
        )]
        append_system_prompt: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        agents: Option<Value>,
    },
    /// Catch-all that carries the raw payload through. Used both for SDK
    /// subtypes the bridge doesn't model (mcp_*) and for forward-compat with
    /// future claude releases.
    #[serde(other, deserialize_with = "deserialize_ignored_subtype")]
    Other,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ClaudeUserMessageEnvelope {
    pub message: ClaudeUserMessage,
    /// Anthropic SDK echoes `parent_tool_use_id` for nested-agent input;
    /// optional on inbound.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_tool_use_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ClaudeUserMessage {
    pub role: ClaudeUserRole,
    pub content: ClaudeUserContent,
}

/// Literal `"user"` discriminator.
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum ClaudeUserRole {
    #[default]
    User,
}

/// Anthropic SDK accepts `string | ContentBlock[]` for user messages.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum ClaudeUserContent {
    Text(String),
    Blocks(Vec<ClaudeUserContentBlock>),
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClaudeUserContentBlock {
    Text(ClaudeTextBlock),
    Image(ClaudeImageBlock),
    /// Tool result input from a sub-message (e.g. when the bridge intercepts
    /// approvals and feeds a synthesized tool result back). Kept as opaque
    /// JSON because the structure is large and bridge code does not edit it.
    ToolResult(Value),
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ClaudeTextBlock {
    pub text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ClaudeImageBlock {
    pub source: ClaudeImageSource,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClaudeImageSource {
    Base64 { media_type: String, data: String },
    Url { url: String },
}

// ============================================================================
// Outbound: claude → bridge on stdout
// ============================================================================

/// Demultiplexer for every line claude writes to stdout. Each line is exactly
/// one of these variants; the reader task in `process.rs` parses the line and
/// broadcasts a [`ClaudeEvent`] wrapping the result.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClaudeOutbound {
    System(SystemEvent),
    StreamEvent(StreamEventEnvelope),
    Assistant(AssistantEnvelope),
    User(UserEnvelope),
    RateLimitEvent(RateLimitEnvelope),
    Result(ResultEnvelope),
    /// Liveness ping from claude. Per the SDK protocol, MUST be silently
    /// ignored — failing to do so floods the reader's parse-error log.
    KeepAlive,
    /// claude → bridge in-band control RPC (e.g. `can_use_tool`,
    /// `hook_callback`, `mcp_message`). Bridge ignores in v1; permission
    /// bridging is a v2 follow-up (#13).
    ControlRequest(serde_json::Value),
    /// Reply to a bridge → claude `control_request`. The reader task peels
    /// `request_id` off and routes the payload to the matching pending-control
    /// oneshot in `pool::process` before broadcasting; the translator then
    /// silently drops the broadcast copy. Modeled as a typed envelope so the
    /// router doesn't reach into a `Value`.
    ControlResponse(ControlResponseEnvelope),
    /// Compact text summary stream. Not surfaced to codex in v1.
    StreamlinedText(serde_json::Value),
    /// Compact tool-use summary stream. Not surfaced to codex in v1.
    StreamlinedToolUseSummary(serde_json::Value),
}

// ----- control responses ---------------------------------------------------

/// `{"type":"control_response","response":{"request_id":"<uuid>","subtype":"success"|"error",...}}`.
///
/// **Wire-quirk:** `request_id` is nested INSIDE the outer `response` object
/// (the SDK looks it up at `Q.response.request_id`), NOT at top level. The
/// `response` field on `Success` carries the subtype-specific reply payload;
/// `Error` carries an `error` string. The bridge parses just enough to bucket
/// success vs. error and route by `request_id`; the inner payload is opaque
/// so new SDK reply shapes pass through without a schema bump.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ControlResponseEnvelope {
    pub response: ControlResponseInner,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "subtype", rename_all = "snake_case")]
pub enum ControlResponseInner {
    Success {
        request_id: String,
        /// Subtype-specific reply payload. For `interrupt` claude sends
        /// `null`; for `rewind_files` this is the rewound state; for
        /// `can_use_tool` (when the bridge is acting as the tool-permission
        /// server, the SDK echoes back our `{behavior:..., ...}`). Opaque.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        response: Option<Value>,
    },
    Error {
        request_id: String,
        error: String,
    },
}

impl ControlResponseInner {
    pub fn request_id(&self) -> &str {
        match self {
            Self::Success { request_id, .. } | Self::Error { request_id, .. } => request_id,
        }
    }
}

/// Surface the response/error shape back to `request_control`'s caller. The
/// outer pool-side enum we expose stays subtype-tagged for ergonomics; the
/// `request_id` field inside the wire envelope has already been peeled off
/// by the reader for routing.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "subtype", rename_all = "snake_case")]
pub enum ControlResponseBody {
    Success {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        response: Option<Value>,
    },
    Error {
        error: String,
    },
}

impl ControlResponseBody {
    pub fn from_inner(inner: ControlResponseInner) -> Self {
        match inner {
            ControlResponseInner::Success { response, .. } => Self::Success { response },
            ControlResponseInner::Error { error, .. } => Self::Error { error },
        }
    }
}

// ----- system ----------------------------------------------------------------

/// `{"type":"system","subtype":"init"|"status"|...,...}`.
///
/// Variants are tagged on `subtype`. The shape varies enough between subtypes
/// (init carries 30+ fields; status is just a string) that we model them
/// individually. Unknown subtypes degrade to [`SystemEvent::Other`] so we
/// never lose a line.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "subtype", rename_all = "snake_case")]
pub enum SystemEvent {
    /// `SystemInit` is significantly larger than the other variants (~330B
    /// vs ~70B), so boxed to keep the enum cheap to clone — every
    /// translator subscriber receives a `ClaudeEvent` clone per stdout
    /// line.
    Init(Box<SystemInit>),
    Status(SystemStatus),
    /// Catch-all for future subtypes (e.g. claude could add `system/idle`,
    /// `system/upgrade_available`). Bridge logs and forwards the payload as
    /// opaque JSON.
    #[serde(other, deserialize_with = "deserialize_ignored_subtype")]
    Other,
}

fn deserialize_ignored_subtype<'de, D>(_d: D) -> Result<(), D::Error>
where
    D: serde::Deserializer<'de>,
{
    Ok(())
}

/// Carries the init signal the bridge waits on before sending the first
/// inbound user message. Fields are kept lossy on purpose — we capture the
/// ones the bridge actually consumes (`session_id`, `cwd`, `model`,
/// caches for `mcpServerStatus/list` / `skills/list`) and let the rest pass
/// through `extra` as opaque JSON.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SystemInit {
    pub session_id: String,
    pub cwd: String,
    pub model: String,
    #[serde(default)]
    pub tools: Vec<String>,
    #[serde(default)]
    pub mcp_servers: Vec<McpServerInit>,
    #[serde(default)]
    pub slash_commands: Vec<String>,
    #[serde(default)]
    pub agents: Vec<String>,
    #[serde(default)]
    pub skills: Vec<String>,
    #[serde(
        default,
        rename = "permissionMode",
        skip_serializing_if = "Option::is_none"
    )]
    pub permission_mode: Option<String>,
    #[serde(
        default,
        rename = "apiKeySource",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_key_source: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub claude_code_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_style: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// `memory_paths`, `plugins`, `analytics_disabled`, `fast_mode_state`,
    /// future additions. Kept as raw JSON so the wire is preserved without
    /// hand-mirroring schemas the bridge does not introspect.
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

/// MCP server entry from `system/init.mcp_servers`. Cached by the bridge for
/// `mcpServerStatus/list`. Unknown fields preserved via `extra`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct McpServerInit {
    pub name: String,
    pub status: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SystemStatus {
    pub status: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

// ----- stream_event ---------------------------------------------------------

/// `{"type":"stream_event","event":{...},"session_id":..,"parent_tool_use_id":..,"uuid":..}`.
///
/// `event` is the Anthropic SDK `RawMessageStreamEvent` family — translation
/// happens in `claude_translate`. `parent_tool_use_id` carries the
/// subagent-hierarchy stamp the translator uses to fill `parent_item_id` on
/// emitted notifications.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct StreamEventEnvelope {
    pub event: RawAnthropicEvent,
    pub session_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_tool_use_id: Option<String>,
    pub uuid: String,
    /// Time-to-first-token populated only on `message_start` envelopes. Kept
    /// for parity with the wire but the bridge does not surface it today.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ttft_ms: Option<u64>,
}

/// Anthropic SDK `RawMessageStreamEvent` union, tagged on `type`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RawAnthropicEvent {
    MessageStart {
        message: Value,
    },
    ContentBlockStart {
        index: u32,
        content_block: ContentBlock,
    },
    ContentBlockDelta {
        index: u32,
        delta: ContentBlockDelta,
    },
    ContentBlockStop {
        index: u32,
    },
    MessageDelta {
        delta: Value,
        usage: Value,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        context_management: Option<Value>,
    },
    MessageStop,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlock {
    Text {
        #[serde(default)]
        text: String,
    },
    Thinking {
        #[serde(default)]
        thinking: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        signature: Option<String>,
    },
    ToolUse {
        id: String,
        name: String,
        #[serde(default)]
        input: Value,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlockDelta {
    TextDelta { text: String },
    ThinkingDelta { thinking: String },
    SignatureDelta { signature: String },
    InputJsonDelta { partial_json: String },
}

// ----- assistant / user (snapshots) -----------------------------------------

/// `{"type":"assistant","message":{...},"parent_tool_use_id":..,"session_id":..,"uuid":..}`.
///
/// Snapshot of the assistant message after each content block close. The
/// translator ignores these (deltas are authoritative) but the bridge keeps
/// them parseable to forward future structured fields without breaking.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AssistantEnvelope {
    pub message: Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_tool_use_id: Option<String>,
    pub session_id: String,
    pub uuid: String,
}

/// `{"type":"user","message":{...},...}` — claude emits these for tool
/// results coming back from its own internal tool loop. The translator pairs
/// each `tool_result` block with the matching `tool_use` it opened earlier.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct UserEnvelope {
    pub message: Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_tool_use_id: Option<String>,
    pub session_id: String,
    pub uuid: String,
    /// Structured `(stdout, stderr, interrupted, isImage, noOutputExpected)`
    /// payload claude attaches to Bash and other tool-result envelopes.
    /// Lives at the top level (sibling of `message`); on the live wire the
    /// field is `tool_use_result`, on disk it is camelCase `toolUseResult`,
    /// so we accept both via serde aliases. Opaque to the protocol layer —
    /// the translator inspects it.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "toolUseResult"
    )]
    pub tool_use_result: Option<Value>,
}

// ----- rate_limit_event -----------------------------------------------------

/// `{"type":"rate_limit_event","rate_limit_info":{...},"uuid":..,"session_id":..}`.
///
/// Cached on the bridge state for `account/rateLimits/read` and surfaced as a
/// `warning` notification when status flips off `allowed`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RateLimitEnvelope {
    pub rate_limit_info: RateLimitInfo,
    pub uuid: String,
    pub session_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RateLimitInfo {
    pub status: String,
    #[serde(default, rename = "resetsAt", skip_serializing_if = "Option::is_none")]
    pub resets_at: Option<i64>,
    #[serde(
        default,
        rename = "rateLimitType",
        skip_serializing_if = "Option::is_none"
    )]
    pub rate_limit_type: Option<String>,
    #[serde(
        default,
        rename = "overageStatus",
        skip_serializing_if = "Option::is_none"
    )]
    pub overage_status: Option<String>,
    #[serde(
        default,
        rename = "isUsingOverage",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_using_overage: Option<bool>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

// ----- result ---------------------------------------------------------------

/// Terminal envelope: `{"type":"result","subtype":..,...}`. Triggers
/// `mark_idle(thread_id)` and unblocks the per-turn pump.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ResultEnvelope {
    pub subtype: String,
    #[serde(default)]
    pub is_error: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_api_ms: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub num_turns: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<String>,
    pub session_id: String,
    pub uuid: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_cost_usd: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_usage: Option<Value>,
    #[serde(default)]
    pub permission_denials: Vec<Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub terminal_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_error_status: Option<Value>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, Value>,
}

// ============================================================================
// Pool-internal broadcast event
// ============================================================================
//
// `ClaudeEvent` is what the pool's `broadcast::Sender` publishes to all
// translator subscribers. For now it is a thin wrapper around `ClaudeOutbound`
// — the bridge does not need to enrich the wire payload before broadcasting.
// Kept as a separate type so future bookkeeping (e.g. arrival timestamps for
// debugging) can be added without breaking subscribers.

#[derive(Debug, Clone)]
pub struct ClaudeEvent {
    pub payload: ClaudeOutbound,
}

impl ClaudeEvent {
    pub fn new(payload: ClaudeOutbound) -> Self {
        Self { payload }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;
    use serde_json::json;

    /// Deserialize a JSON `Value` into `T` and assert the parsed payload.
    /// We don't round-trip serialize/deserialize here because claude's wire
    /// is more permissive than ours (lots of numeric keys with defaults that
    /// our serializer would omit), and test stability matters more than
    /// byte-exact equality. The shapes-the-bridge-introspects fields are what
    /// the assertions verify.
    fn parse<T: for<'de> Deserialize<'de>>(value: Value) -> T {
        serde_json::from_value(value).expect("parse")
    }

    #[test]
    fn parses_system_init_from_live_probe() {
        // Trimmed version of the live-probe init line documented in the
        // module docstring.
        let init: ClaudeOutbound = parse(json!({
            "type": "system",
            "subtype": "init",
            "cwd": "/private/tmp",
            "session_id": "ddbbff6f-8b44-4531-b445-2a9043f8bad6",
            "tools": ["Bash", "Edit"],
            "mcp_servers": [
                {"name":"claude.ai Google Drive","status":"needs-auth"}
            ],
            "model": "claude-haiku-4-5-20251001",
            "permissionMode": "bypassPermissions",
            "slash_commands": ["init", "review"],
            "agents": ["Explore"],
            "skills": ["debug", "simplify"],
            "apiKeySource": "none",
            "claude_code_version": "2.1.121",
            "output_style": "default",
            "uuid": "08338b92-5973-497f-bb04-877a6e3cfb61",
            "memory_paths": {"auto": "/tmp/memory/"}
        }));
        match init {
            ClaudeOutbound::System(SystemEvent::Init(payload)) => {
                assert_eq!(payload.session_id, "ddbbff6f-8b44-4531-b445-2a9043f8bad6");
                assert_eq!(payload.cwd, "/private/tmp");
                assert_eq!(payload.model, "claude-haiku-4-5-20251001");
                assert_eq!(payload.tools, vec!["Bash", "Edit"]);
                assert_eq!(payload.mcp_servers.len(), 1);
                assert_eq!(payload.mcp_servers[0].name, "claude.ai Google Drive");
                assert_eq!(payload.mcp_servers[0].status, "needs-auth");
                assert_eq!(
                    payload.permission_mode.as_deref(),
                    Some("bypassPermissions")
                );
                assert_eq!(payload.claude_code_version.as_deref(), Some("2.1.121"));
                assert!(payload.extra.contains_key("memory_paths"));
            }
            other => panic!("expected System(Init), got {other:?}"),
        }
    }

    #[test]
    fn parses_system_status() {
        let evt: ClaudeOutbound = parse(json!({
            "type": "system",
            "subtype": "status",
            "status": "requesting",
            "uuid": "u1",
            "session_id": "s1"
        }));
        match evt {
            ClaudeOutbound::System(SystemEvent::Status(s)) => {
                assert_eq!(s.status, "requesting");
                assert_eq!(s.uuid.as_deref(), Some("u1"));
            }
            other => panic!("expected System(Status), got {other:?}"),
        }
    }

    #[test]
    fn parses_unknown_system_subtype_as_other() {
        let evt: ClaudeOutbound = parse(json!({
            "type": "system",
            "subtype": "future_thing",
            "anything": "goes"
        }));
        match evt {
            ClaudeOutbound::System(SystemEvent::Other) => {}
            other => panic!("expected System(Other), got {other:?}"),
        }
    }

    #[test]
    fn parses_stream_event_message_start_with_parent_tool_use_id() {
        let evt: ClaudeOutbound = parse(json!({
            "type": "stream_event",
            "event": {
                "type": "message_start",
                "message": {"id": "msg_1", "model": "haiku"}
            },
            "session_id": "s1",
            "parent_tool_use_id": "toolu_outer",
            "uuid": "u1",
            "ttft_ms": 793
        }));
        match evt {
            ClaudeOutbound::StreamEvent(env) => {
                assert_eq!(env.session_id, "s1");
                assert_eq!(env.parent_tool_use_id.as_deref(), Some("toolu_outer"));
                assert_eq!(env.ttft_ms, Some(793));
                match env.event {
                    RawAnthropicEvent::MessageStart { message } => {
                        assert_eq!(message["id"], "msg_1");
                    }
                    other => panic!("expected MessageStart, got {other:?}"),
                }
            }
            other => panic!("expected StreamEvent, got {other:?}"),
        }
    }

    #[test]
    fn parses_content_block_start_tool_use_with_input() {
        let evt: RawAnthropicEvent = parse(json!({
            "type": "content_block_start",
            "index": 0,
            "content_block": {
                "type": "tool_use",
                "id": "toolu_1",
                "name": "Bash",
                "input": {}
            }
        }));
        match evt {
            RawAnthropicEvent::ContentBlockStart {
                index,
                content_block: ContentBlock::ToolUse { id, name, .. },
            } => {
                assert_eq!(index, 0);
                assert_eq!(id, "toolu_1");
                assert_eq!(name, "Bash");
            }
            other => panic!("expected ToolUse content block, got {other:?}"),
        }
    }

    #[test]
    fn parses_content_block_delta_variants() {
        let text: ContentBlockDelta = parse(json!({"type":"text_delta","text":"Hey"}));
        assert!(matches!(text, ContentBlockDelta::TextDelta { ref text } if text == "Hey"));

        let thinking: ContentBlockDelta =
            parse(json!({"type":"thinking_delta","thinking":"...thoughts"}));
        assert!(matches!(thinking, ContentBlockDelta::ThinkingDelta { .. }));

        let sig: ContentBlockDelta =
            parse(json!({"type":"signature_delta","signature":"sig-base64"}));
        assert!(matches!(sig, ContentBlockDelta::SignatureDelta { .. }));

        let input: ContentBlockDelta =
            parse(json!({"type":"input_json_delta","partial_json":"{\"command\":"}));
        match input {
            ContentBlockDelta::InputJsonDelta { partial_json } => {
                assert_eq!(partial_json, r#"{"command":"#);
            }
            other => panic!("expected InputJsonDelta, got {other:?}"),
        }
    }

    #[test]
    fn parses_rate_limit_event() {
        let evt: ClaudeOutbound = parse(json!({
            "type": "rate_limit_event",
            "rate_limit_info": {
                "status": "allowed",
                "resetsAt": 1777345200_i64,
                "rateLimitType": "five_hour",
                "overageStatus": "rejected",
                "isUsingOverage": false,
                "overageDisabledReason": "org_level_disabled_until"
            },
            "uuid": "u1",
            "session_id": "s1"
        }));
        match evt {
            ClaudeOutbound::RateLimitEvent(env) => {
                assert_eq!(env.rate_limit_info.status, "allowed");
                assert_eq!(env.rate_limit_info.resets_at, Some(1777345200));
                assert_eq!(env.rate_limit_info.is_using_overage, Some(false));
                assert!(
                    env.rate_limit_info
                        .extra
                        .contains_key("overageDisabledReason")
                );
            }
            other => panic!("expected RateLimitEvent, got {other:?}"),
        }
    }

    #[test]
    fn parses_result_success_with_permission_denials_empty() {
        let evt: ClaudeOutbound = parse(json!({
            "type": "result",
            "subtype": "success",
            "is_error": false,
            "duration_ms": 1720,
            "duration_api_ms": 2700,
            "num_turns": 1,
            "result": "Hey!",
            "stop_reason": "end_turn",
            "session_id": "s1",
            "uuid": "u1",
            "total_cost_usd": 0.011,
            "usage": {"input_tokens": 10},
            "permission_denials": [],
            "terminal_reason": "completed"
        }));
        match evt {
            ClaudeOutbound::Result(r) => {
                assert_eq!(r.subtype, "success");
                assert!(!r.is_error);
                assert_eq!(r.result.as_deref(), Some("Hey!"));
                assert_eq!(r.permission_denials.len(), 0);
                assert_eq!(r.terminal_reason.as_deref(), Some("completed"));
            }
            other => panic!("expected Result, got {other:?}"),
        }
    }

    #[test]
    fn parses_result_error_with_denials() {
        let evt: ClaudeOutbound = parse(json!({
            "type": "result",
            "subtype": "error_during_execution",
            "is_error": true,
            "session_id": "s1",
            "uuid": "u1",
            "permission_denials": [{"tool":"Bash","reason":"denied"}]
        }));
        match evt {
            ClaudeOutbound::Result(r) => {
                assert_eq!(r.subtype, "error_during_execution");
                assert!(r.is_error);
                assert_eq!(r.permission_denials.len(), 1);
            }
            other => panic!("expected Result, got {other:?}"),
        }
    }

    #[test]
    fn parses_assistant_envelope_passes_message_through() {
        let evt: ClaudeOutbound = parse(json!({
            "type": "assistant",
            "message": {"id": "msg_1", "content": [{"type":"text","text":"Hey"}]},
            "parent_tool_use_id": null,
            "session_id": "s1",
            "uuid": "u1"
        }));
        match evt {
            ClaudeOutbound::Assistant(env) => {
                assert_eq!(env.message["id"], "msg_1");
                assert_eq!(env.parent_tool_use_id, None);
            }
            other => panic!("expected Assistant, got {other:?}"),
        }
    }

    #[test]
    fn parses_user_tool_result_envelope() {
        let evt: ClaudeOutbound = parse(json!({
            "type": "user",
            "message": {
                "role": "user",
                "content": [{
                    "type": "tool_result",
                    "tool_use_id": "toolu_1",
                    "content": "exit code: 0\n"
                }]
            },
            "session_id": "s1",
            "uuid": "u1"
        }));
        match evt {
            ClaudeOutbound::User(env) => {
                assert_eq!(env.message["content"][0]["tool_use_id"], "toolu_1");
            }
            other => panic!("expected User, got {other:?}"),
        }
    }

    #[test]
    fn parses_keep_alive_silently() {
        let evt: ClaudeOutbound = parse(json!({"type": "keep_alive"}));
        assert!(matches!(evt, ClaudeOutbound::KeepAlive));
    }

    #[test]
    fn parses_control_request_as_opaque_value() {
        let evt: ClaudeOutbound = parse(json!({
            "type": "control_request",
            "request_id": "r1",
            "request": {"subtype": "can_use_tool", "tool_name": "Bash"}
        }));
        match evt {
            ClaudeOutbound::ControlRequest(v) => {
                assert_eq!(v["request_id"], "r1");
                assert_eq!(v["request"]["subtype"], "can_use_tool");
            }
            other => panic!("expected ControlRequest, got {other:?}"),
        }
    }

    #[test]
    fn parses_control_response_success_with_nested_request_id() {
        // Wire-quirk: the SDK looks up `Q.response.request_id` — request_id
        // lives INSIDE the outer `response`, not at top level.
        let evt: ClaudeOutbound = parse(json!({
            "type": "control_response",
            "response": {"request_id": "r1", "subtype": "success"}
        }));
        match evt {
            ClaudeOutbound::ControlResponse(env) => {
                assert_eq!(env.response.request_id(), "r1");
                assert!(matches!(env.response, ControlResponseInner::Success { .. }));
            }
            other => panic!("expected ControlResponse, got {other:?}"),
        }
    }

    #[test]
    fn parses_control_response_success_carries_inner_response_payload() {
        // rewind_files / can_use_tool replies carry an inner `response`
        // payload alongside subtype + request_id.
        let evt: ClaudeOutbound = parse(json!({
            "type": "control_response",
            "response": {
                "request_id": "r1",
                "subtype": "success",
                "response": {"rewound_to": "msg_42", "files_changed": 3}
            }
        }));
        match evt {
            ClaudeOutbound::ControlResponse(env) => match env.response {
                ControlResponseInner::Success {
                    request_id,
                    response,
                } => {
                    assert_eq!(request_id, "r1");
                    let payload = response.expect("payload");
                    assert_eq!(payload["rewound_to"], "msg_42");
                    assert_eq!(payload["files_changed"], 3);
                }
                other => panic!("expected Success, got {other:?}"),
            },
            other => panic!("expected ControlResponse, got {other:?}"),
        }
    }

    #[test]
    fn parses_control_response_error() {
        let evt: ClaudeOutbound = parse(json!({
            "type": "control_response",
            "response": {
                "request_id": "r2",
                "subtype": "error",
                "error": "interrupt timed out"
            }
        }));
        match evt {
            ClaudeOutbound::ControlResponse(env) => match env.response {
                ControlResponseInner::Error { error, request_id } => {
                    assert_eq!(error, "interrupt timed out");
                    assert_eq!(request_id, "r2");
                }
                other => panic!("expected Error, got {other:?}"),
            },
            other => panic!("expected ControlResponse, got {other:?}"),
        }
    }

    #[test]
    fn outbound_control_request_interrupt_serializes() {
        let req = ClaudeInbound::ControlRequest(ControlRequestEnvelope {
            request_id: "abc".into(),
            request: ControlRequestBody::Interrupt,
        });
        let serialized = serde_json::to_value(&req).unwrap();
        assert_eq!(
            serialized,
            json!({
                "type": "control_request",
                "request_id": "abc",
                "request": {"subtype": "interrupt"}
            })
        );
        let back: ClaudeInbound = serde_json::from_value(serialized).unwrap();
        assert_eq!(back, req);
    }

    #[test]
    fn outbound_control_request_set_model_serializes() {
        let req = ClaudeInbound::ControlRequest(ControlRequestEnvelope {
            request_id: "abc".into(),
            request: ControlRequestBody::SetModel {
                model: "sonnet".into(),
            },
        });
        let serialized = serde_json::to_value(&req).unwrap();
        assert_eq!(
            serialized,
            json!({
                "type": "control_request",
                "request_id": "abc",
                "request": {"subtype": "set_model", "model": "sonnet"}
            })
        );
    }

    #[test]
    fn outbound_control_request_rewind_files_serializes() {
        let req = ClaudeInbound::ControlRequest(ControlRequestEnvelope {
            request_id: "r1".into(),
            request: ControlRequestBody::RewindFiles {
                user_message_id: "msg_42".into(),
                dry_run: Some(false),
            },
        });
        let serialized = serde_json::to_value(&req).unwrap();
        assert_eq!(serialized["request"]["subtype"], "rewind_files");
        assert_eq!(serialized["request"]["user_message_id"], "msg_42");
        assert_eq!(serialized["request"]["dry_run"], false);
    }

    #[test]
    fn outbound_control_response_success_serializes_with_nested_request_id() {
        // Bridge → claude when answering a `can_use_tool` permission ask.
        // Wire-quirk: request_id MUST be inside the outer `response`.
        let env = ClaudeInbound::ControlResponse(OutboundControlResponseEnvelope {
            response: OutboundControlResponseInner::Success {
                request_id: "r1".into(),
                response: Some(json!({"behavior": "allow"})),
            },
        });
        let serialized = serde_json::to_value(&env).unwrap();
        assert_eq!(
            serialized,
            json!({
                "type": "control_response",
                "response": {
                    "request_id": "r1",
                    "subtype": "success",
                    "response": {"behavior": "allow"}
                }
            })
        );
    }

    #[test]
    fn outbound_control_response_error_serializes() {
        let env = ClaudeInbound::ControlResponse(OutboundControlResponseEnvelope {
            response: OutboundControlResponseInner::Error {
                request_id: "r1".into(),
                error: "user dismissed".into(),
            },
        });
        let serialized = serde_json::to_value(&env).unwrap();
        assert_eq!(
            serialized,
            json!({
                "type": "control_response",
                "response": {
                    "request_id": "r1",
                    "subtype": "error",
                    "error": "user dismissed"
                }
            })
        );
    }

    #[test]
    fn outbound_control_cancel_serializes() {
        let req = ClaudeInbound::ControlCancelRequest(ControlCancelEnvelope {
            request_id: "r1".into(),
        });
        let serialized = serde_json::to_value(&req).unwrap();
        assert_eq!(
            serialized,
            json!({
                "type": "control_cancel_request",
                "request_id": "r1"
            })
        );
    }

    #[test]
    fn parses_streamlined_envelopes() {
        let evt: ClaudeOutbound = parse(json!({"type": "streamlined_text", "text": "ok"}));
        assert!(matches!(evt, ClaudeOutbound::StreamlinedText(_)));
        let evt: ClaudeOutbound =
            parse(json!({"type": "streamlined_tool_use_summary", "tool": "Bash"}));
        assert!(matches!(evt, ClaudeOutbound::StreamlinedToolUseSummary(_)));
    }

    #[test]
    fn user_inbound_text_content_round_trips() {
        let inbound = ClaudeInbound::User(ClaudeUserMessageEnvelope {
            message: ClaudeUserMessage {
                role: ClaudeUserRole::User,
                content: ClaudeUserContent::Text("hello".into()),
            },
            parent_tool_use_id: None,
        });
        let serialized = serde_json::to_value(&inbound).unwrap();
        assert_eq!(
            serialized,
            json!({
                "type": "user",
                "message": {"role": "user", "content": "hello"}
            })
        );
        let back: ClaudeInbound = serde_json::from_value(serialized).unwrap();
        assert_eq!(back, inbound);
    }

    #[test]
    fn user_inbound_blocks_with_image_round_trips() {
        let inbound = ClaudeInbound::User(ClaudeUserMessageEnvelope {
            message: ClaudeUserMessage {
                role: ClaudeUserRole::User,
                content: ClaudeUserContent::Blocks(vec![
                    ClaudeUserContentBlock::Text(ClaudeTextBlock {
                        text: "see this".into(),
                    }),
                    ClaudeUserContentBlock::Image(ClaudeImageBlock {
                        source: ClaudeImageSource::Base64 {
                            media_type: "image/png".into(),
                            data: "AAA".into(),
                        },
                    }),
                ]),
            },
            parent_tool_use_id: None,
        });
        let serialized = serde_json::to_value(&inbound).unwrap();
        assert_eq!(
            serialized,
            json!({
                "type": "user",
                "message": {
                    "role": "user",
                    "content": [
                        {"type":"text","text":"see this"},
                        {"type":"image","source":{
                            "type":"base64","media_type":"image/png","data":"AAA"
                        }}
                    ]
                }
            })
        );
        let back: ClaudeInbound = serde_json::from_value(serialized).unwrap();
        assert_eq!(back, inbound);
    }
}
